In [1]:
umbral = 0.5
tasa_de_aprendizaje = 0.1
#pesos = [0,0,0]
import numpy as np
pesos = np.random.uniform(-1, 1, size=3)
print(pesos)
conjunto_de_formacion = [((1,0,0),1), ((1,0,1),1), ((1,1,0),1), ((1,1,1),1)]

def producto_punto(valores, pesos):
  return sum([valor*peso for valor, peso in zip(valores, pesos)])

while True:
  print('-' * 60)
  contador_de_errores = 0
  for vector_de_entrada, salida_deseada in conjunto_de_formacion:
    print(pesos)
    resultado = producto_punto(vector_de_entrada, pesos)>umbral
    error = salida_deseada - resultado
    if error != 0:
      contador_de_errores += 1
      for indice, valor in enumerate(vector_de_entrada):
        pesos[indice] += tasa_de_aprendizaje * error * valor
  if contador_de_errores == 0:
    break

[-0.88170544  0.22454928 -0.37207867]
------------------------------------------------------------
[-0.88170544  0.22454928 -0.37207867]
[-0.78170544  0.22454928 -0.37207867]
[-0.68170544  0.22454928 -0.27207867]
[-0.58170544  0.32454928 -0.27207867]
------------------------------------------------------------
[-0.48170544  0.42454928 -0.17207867]
[-0.38170544  0.42454928 -0.17207867]
[-0.28170544  0.42454928 -0.07207867]
[-0.18170544  0.52454928 -0.07207867]
------------------------------------------------------------
[-0.08170544  0.62454928  0.02792133]
[0.01829456 0.62454928 0.02792133]
[0.11829456 0.62454928 0.12792133]
[0.11829456 0.62454928 0.12792133]
------------------------------------------------------------
[0.11829456 0.62454928 0.12792133]
[0.21829456 0.62454928 0.12792133]
[0.31829456 0.62454928 0.22792133]
[0.31829456 0.62454928 0.22792133]
------------------------------------------------------------
[0.31829456 0.62454928 0.22792133]
[0.41829456 0.62454928 0.22792133]


In [3]:
conjunto_de_formacion = [((1,0,0),1), ((1,0,1),1), ((1,1,0),1), ((1,1,1),1)]

In [6]:
w1 = 0.837719
w2 = -0.25595254
w3 = -0.16871844

In [7]:
def activacion(x):
  if x > 0.5:
    return 1
  else:
    return 0

In [8]:
X1 = 1
X2 = 1
X3 = 1
resultado = w1*X1 + w2*X2 + w3*X3
activacion(resultado)

0

In [9]:
import numpy as np
pesos = np.random.uniform(-1, 1, size=2)
b = np.random.uniform(-1, 1)
pesos, b
#print(pesos)

(array([-0.13187823,  0.34781127]), -0.5714131065156924)